# Generated by Django 6.0.7 on 2026-07-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('page', models.CharField(max_length=500)),
                ('datetime', models.TimeField(auto_now=True)),
            ],
        ),
    ]
